1. Из наборов изображений, выбрать по 135 изображений каждой цифры без шума: a)100/15/20 для обучающей/валидационной/тестовой выборок). В каждой выборке должно содержаться равное количество изображений каждой цифры в вертикальном и горизонтальном положении соответственно.


In [1]:
import os
import random
import shutil
import numpy as np
from PIL import Image, ImageDraw
import cv2

nb_images = 700  # Количество изображений каждой цифры
# Создание папок для тренировочной и тестовой выборок
train_dir = f'train_data_{nb_images}/train'
os.makedirs(train_dir, exist_ok=True)

def create_directory(dir_name):
    if os.path.exists(dir_name):
        shutil.rmtree(dir_name)
    os.makedirs(dir_name, exist_ok=True)
    os.makedirs(os.path.join(dir_name, "0"))
    os.makedirs(os.path.join(dir_name, "1"))
    os.makedirs(os.path.join(dir_name, "3"))
    os.makedirs(os.path.join(dir_name, "8"))

create_directory(train_dir)

# Функция для генерации изображений
def generate_images(digits, num_images, directory):
    for i in range(num_images):
        # Создание белого фона
        img = Image.new('L', (100, 100), color='white')
        draw = ImageDraw.Draw(img)

        # Создание изображения цифры
        digit_img = Image.new('L', (20, 50), color='white')
        digit_draw = ImageDraw.Draw(digit_img)
        digit_draw.text((0, 0), str(digit), fill='black')

        # Случайное местоположение цифры
        x = random.randint(0, 80)
        y = random.randint(0, 50)
        img.paste(digit_img, (x, y))

        # Поворот изображения (вертикально или горизонтально)
        if i % 2:
            img = img.transpose(Image.ROTATE_90)

        # Преобразование изображения PIL в изображение OpenCV
        cv_img = cv2.cvtColor(np.array(img), cv2.COLOR_GRAY2BGR)

        # Сохранение изображения
        cv2.imwrite(os.path.join(f'{directory}', f'{digit}_{i}.png'), cv_img)

# Генерация изображений для тренировочной выборки
for digit in [0, 1, 3, 8]:
  generate_images([0, 1, 3, 8], nb_images, f'{train_dir}/{digit}')

In [2]:
test_dir = 'test_data_1'
os.makedirs(test_dir, exist_ok=True)

def create_directory(dir_name):
    #if os.path.exists(dir_name):
       # shutil.rmtree(dir_name)
    os.makedirs(dir_name, exist_ok=True)
    os.makedirs(os.path.join(dir_name, "0"))
    os.makedirs(os.path.join(dir_name, "1"))
    os.makedirs(os.path.join(dir_name, "3"))
    os.makedirs(os.path.join(dir_name, "8"))

create_directory(test_dir)

# Функция для генерации изображений
def generate_images(digits, num_images, directory):
    for i in range(num_images):
        # Создание белого фона
        img = Image.new('L', (100, 100), color='white')
        draw = ImageDraw.Draw(img)

        # Создание изображения цифры
        digit_img = Image.new('L', (20, 50), color='white')
        digit_draw = ImageDraw.Draw(digit_img)
        digit_draw.text((0, 0), str(digit), fill='black')

        # Случайное местоположение цифры
        x = random.randint(0, 80)
        y = random.randint(0, 50)
        img.paste(digit_img, (x, y))

        # Поворот изображения (вертикально или горизонтально)
        if i % 2:
            img = img.transpose(Image.ROTATE_90)

        # Преобразование изображения PIL в изображение OpenCV
        cv_img = cv2.cvtColor(np.array(img), cv2.COLOR_GRAY2BGR)

        # Сохранение изображения
        cv2.imwrite(os.path.join(f'{directory}', f'{digit}_{i}.png'), cv_img)

# Генерация изображений для тестовой выборки
for digit in [0, 1, 3, 8]:
  generate_images([0, 1, 3, 8], 20, f'{test_dir}/{digit}')

In [3]:
nb_images = 700  # Количество изображений каждой цифры
val_nb_images = 100  # Количество изображений каждой цифры
# Создание папок для тренировочной и тестовой выборок
val_dir = f'train_data_{nb_images}/val'
os.makedirs(val_dir, exist_ok=True)

def create_directory(dir_name):
    #if os.path.exists(dir_name):
        #shutil.rmtree(dir_name)
    os.makedirs(dir_name, exist_ok=True)
    os.makedirs(os.path.join(dir_name, "0"))
    os.makedirs(os.path.join(dir_name, "1"))
    os.makedirs(os.path.join(dir_name, "3"))
    os.makedirs(os.path.join(dir_name, "8"))

create_directory(val_dir)

# Функция для генерации изображений
def generate_images(digits, num_images, directory):
    for i in range(num_images):
        # Создание белого фона
        img = Image.new('L', (100, 100), color='white')
        draw = ImageDraw.Draw(img)

        # Создание изображения цифры
        digit_img = Image.new('L', (20, 50), color='white')
        digit_draw = ImageDraw.Draw(digit_img)
        digit_draw.text((0, 0), str(digit), fill='black')

        # Случайное местоположение цифры
        x = random.randint(0, 80)
        y = random.randint(0, 50)
        img.paste(digit_img, (x, y))

        # Поворот изображения (вертикально или горизонтально)
        if i % 2:
            img = img.transpose(Image.ROTATE_90)

        # Преобразование изображения PIL в изображение OpenCV
        cv_img = cv2.cvtColor(np.array(img), cv2.COLOR_GRAY2BGR)

        # Сохранение изображения
        cv2.imwrite(os.path.join(f'{directory}', f'{digit}_{i}.png'), cv_img)

# Генерация изображений для тренировочной выборки
for digit in [0, 1, 3, 8]:
  generate_images([0, 1, 3, 8], val_nb_images, f'{val_dir}/{digit}')

2. Реализовать каждую из сверточных нейронных сетей https://keras.io/api/applications/: Xception, ResNet152V2, InceptionResNetV2, DenseNet201, NASNetLarge и вывести результаты классификации на тестовом множестве.
3. Повторить пункт 2, изменив размеры обучающей/валидационной/тестовой выборок для каждой цифры на:
    * b) 250/30/20,
    * c) 400/60/20,
    * d) 700/100/20.



In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.applications import Xception, ResNet152V2, InceptionResNetV2, DenseNet201, NASNetLarge
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import confusion_matrix, classification_report

# Установка параметров
img_height, img_width = 100, 100  # Размер изображений для моделей
num_classes = 4
batch_size = 32

# Пути к данным
nb_images = 700  # Количество изображений в каждой категории для обучения
train_dir = f"train_data_{nb_images}/train"
val_dir = f"train_data_{nb_images}/val"
test_dir = "test_data_1"

# Генераторы данных
train_datagen = ImageDataGenerator(rescale=1./255)
val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical')

val_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical')

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    shuffle=False)

# Создание и обучение моделей
models = [Xception, ResNet152V2, InceptionResNetV2, DenseNet201, NASNetLarge]

for model_type in models:
    base_model = model_type(weights='imagenet', include_top=False, input_shape=(img_height, img_width, 3))

    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(1024, activation='relu')(x)
    predictions = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs=base_model.input, outputs=predictions)

    for layer in base_model.layers:
        layer.trainable = False

    model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

    print(f"\nTraining {model_type.__name__}...")
    model.fit(train_generator, epochs=15, validation_data=val_generator)

    # Оценка модели на тестовом наборе данных
    print(f"\nEvaluating {model_type.__name__} on test data...")
    test_loss, test_acc = model.evaluate(test_generator)
    print(f"Test Accuracy: {test_acc}")

    # Предсказания модели
    predictions = model.predict(test_generator)
    y_pred = np.argmax(predictions, axis=1)
    y_true = test_generator.classes

    # Матрица ошибок
    print("\nConfusion Matrix:")
    print(confusion_matrix(y_true, y_pred))

    # Метрики precision, recall и f1-score
    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=test_generator.class_indices))


Found 2800 images belonging to 4 classes.
Found 400 images belonging to 4 classes.
Found 80 images belonging to 4 classes.
83683744/83683744 [==============================] - 1s 0us/step

Training Xception...
Epoch 1/15
88/88 [==============================] - 14s 69ms/step - loss: 0.8503 - accuracy: 0.6404 - val_loss: 0.6060 - val_accuracy: 0.7375
Epoch 2/15
88/88 [==============================] - 4s 44ms/step - loss: 0.5275 - accuracy: 0.7761 - val_loss: 0.5054 - val_accuracy: 0.7800
Epoch 3/15
88/88 [==============================] - 3s 38ms/step - loss: 0.4308 - accuracy: 0.8136 - val_loss: 0.4783 - val_accuracy: 0.7550
Epoch 4/15
88/88 [==============================] - 3s 36ms/step - loss: 0.3980 - accuracy: 0.8254 - val_loss: 0.4062 - val_accuracy: 0.8150
Epoch 5/15
88/88 [==============================] - 3s 38ms/step - loss: 0.3568 - accuracy: 0.8475 - val_loss: 0.4009 - val_accuracy: 0.8025
Epoch 6/15
88/88 [==============================] - 3s 35ms/step - loss: 0.3165 - ac

3/3 [==============================] - 6s 140ms/step

Confusion Matrix:
[[20  0  0  0]
 [ 0 20  0  0]
 [ 0  0 16  4]
 [ 0  0  3 17]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        20
           3       0.84      0.80      0.82        20
           8       0.81      0.85      0.83        20

    accuracy                           0.91        80
   macro avg       0.91      0.91      0.91        80
weighted avg       0.91      0.91      0.91        80

